output: "{{.Dir}}/README.md"
header: |-
  [![Go Report Card](https://goreportcard.com/badge/github.com/nonsocode/xpress)](https://goreportcard.com/report/github.com/nonsocode/xpress)
  [![Conformance](https://github.com/nonsocode/xpress/actions/workflows/conformance.yml/badge.svg)](https://github.com/nonsocode/xpress/actions/workflows/conformance.yml)
  [![Go Reference](https://pkg.go.dev/badge/github.com/nonsocode/xpress.svg)](https://pkg.go.dev/github.com/nonsocode/xpress)
  [![codecov](https://codecov.io/gh/nonsocode/xpress/branch/master/graph/badge.svg)](https://codecov.io/gh/nonsocode/xpress)
repository:
  url: https://github.com/nonsocode/xpress
  defaultBranch: main
  path: /