# hello world workflow
# this workflow is triggered manually. it runs on ubuntu and just runs a single echo command
name: hello world
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: echo hello world
        run: echo "hello world"

